// This file is part of a Java port of RE2 (https://github.com/google/re2).
// Original RE2 code is Copyright (c) 2009 The RE2 Authors.
// Modifications and Java port Copyright (c) 2026 Eddie Aftandilian.
// Licensed under the BSD 3-Clause License (see LICENSE file).

package dev.eaftan.safere;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Non-recursive tree walker for {@link Regexp} ASTs. Uses an explicit stack to avoid stack overflow
 * on deeply nested expressions.
 *
 * <p>Subclasses override {@link #preVisit}, {@link #postVisit}, {@link #copy}, and {@link
 * #shortVisit} to define the traversal behavior. The walker calls {@code preVisit} before visiting
 * a node's children and {@code postVisit} after all children have been visited.
 *
 * <p>This is a port of RE2's {@code walker-inl.h}.
 *
 * @param <T> the type of value accumulated during the walk
 */
abstract class Walker<T> {

  private final ArrayList<WalkState<T>> stack = new ArrayList<>();
  private boolean stoppedEarly;
  private int maxVisits;

  /**
   * Called before visiting {@code re}'s children.
   *
   * <p>The returned value is passed to {@code postVisit} as {@code preArg} and to children's {@code
   * preVisit} and {@code postVisit} as {@code parentArg}.
   *
   * <p>If this method sets {@code stop[0]} to true, the walk does not recurse into children and the
   * return value is used as the result for this node (as if it were the {@code postVisit} result).
   *
   * @param re the node being visited
   * @param parentArg the accumulated argument from the parent (or {@code topArg} for the root)
   * @param stop single-element array; set {@code stop[0] = true} to skip children
   * @return the value to pass to children and to postVisit
   */
  protected T preVisit(Regexp re, T parentArg, boolean[] stop) {
    return parentArg;
  }

  /**
   * Called after visiting {@code re}'s children.
   *
   * @param re the node being visited
   * @param parentArg the accumulated argument from the parent
   * @param preArg the value returned by preVisit
   * @param childArgs list of values returned by children's postVisit. Empty if there are no
   *     children. Mutable — implementations may modify it (e.g., for coalescing).
   * @return the result for this node
   */
  protected T postVisit(Regexp re, T parentArg, T preArg, List<T> childArgs) {
    return preArg;
  }

  /**
   * Called to copy a value when the walker notices that adjacent children are the same Regexp
   * object. Only used in {@link #walk}, not in {@link #walkExponential}.
   */
  protected T copy(T arg) {
    return arg;
  }

  /**
   * Called to do a quick visit of a node (but not its children) when the visit budget has been
   * exhausted. Should return a value that makes sense for the remaining parent postVisits.
   */
  protected abstract T shortVisit(Regexp re, T parentArg);

  /** Returns true if the walk was cut short due to the visit budget being exhausted. */
  boolean stoppedEarly() {
    return stoppedEarly;
  }

  /**
   * Walks over a regular expression tree, using {@link #copy} to avoid re-visiting shared
   * sub-trees.
   */
  T walk(Regexp re, T topArg) {
    maxVisits = 1_000_000;
    return walkInternal(re, topArg, true);
  }

  /**
   * Walks over a regular expression tree without using {@link #copy}. This can lead to exponential
   * runtimes on cross-linked Regexps (like those generated by Simplify). At most {@code maxVisits}
   * nodes will be visited; after that, {@link #shortVisit} is called instead.
   */
  T walkExponential(Regexp re, T topArg, int maxVisits) {
    this.maxVisits = maxVisits;
    return walkInternal(re, topArg, false);
  }

  private T walkInternal(Regexp re, T topArg, boolean useCopy) {
    stoppedEarly = false;
    stack.clear();

    if (re == null) {
      return topArg;
    }

    stack.add(new WalkState<>(re, topArg));

    for (;;) {
      WalkState<T> s = stack.get(stack.size() - 1);
      re = s.re;
      int nsub = (re.subs != null) ? re.subs.size() : 0;

      if (s.n == -1) {
        // Need to call preVisit.
        if (--maxVisits < 0) {
          stoppedEarly = true;
          T t = shortVisit(re, s.parentArg);
          stack.remove(stack.size() - 1);
          if (stack.isEmpty()) {
            return t;
          }
          WalkState<T> parent = stack.get(stack.size() - 1);
          parent.childArgs.add(t);
          parent.n++;
          continue;
        }
        boolean[] stop = {false};
        s.preArg = preVisit(re, s.parentArg, stop);
        if (stop[0]) {
          T t = s.preArg;
          stack.remove(stack.size() - 1);
          if (stack.isEmpty()) {
            return t;
          }
          WalkState<T> parent = stack.get(stack.size() - 1);
          parent.childArgs.add(t);
          parent.n++;
          continue;
        }
        s.n = 0;
        s.childArgs = new ArrayList<>(nsub);
        // Fall through to child processing.
      }

      // Process children.
      if (nsub > 0 && s.n < nsub) {
        if (useCopy && s.n > 0 && re.subs.get(s.n - 1) == re.subs.get(s.n)) {
          T prev = s.childArgs.get(s.n - 1);
          s.childArgs.add(copy(prev));
          s.n++;
          continue;
        }
        stack.add(new WalkState<>(re.subs.get(s.n), s.preArg));
        continue;
      }

      // All children done (or no children). Call postVisit.
      T t = postVisit(re, s.parentArg, s.preArg, s.childArgs);
      stack.remove(stack.size() - 1);
      if (stack.isEmpty()) {
        return t;
      }
      WalkState<T> parent = stack.get(stack.size() - 1);
      parent.childArgs.add(t);
      parent.n++;
    }
  }

  /** State for a single level in the traversal. */
  private static final class WalkState<T> {
    final Regexp re;
    int n; // -1 means need preVisit; >= 0 is index of next child to process
    final T parentArg;
    T preArg;
    List<T> childArgs = Collections.emptyList();

    WalkState(Regexp re, T parentArg) {
      this.re = re;
      this.n = -1;
      this.parentArg = parentArg;
    }
  }
}
